# Generated by Django 6.0.2 on 2026-02-07 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_url', models.URLField(unique=True)),
                ('provider', models.CharField(max_length=50)),
                ('provider_video_id', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('channel_name', models.CharField(blank=True, max_length=200)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoFormat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('container', models.CharField(max_length=16)),
                ('quality_label', models.CharField(blank=True, max_length=32)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('codec_video', models.CharField(blank=True, max_length=32)),
                ('codec_audio', models.CharField(blank=True, max_length=32)),
                ('is_audio_only', models.BooleanField(default=False)),
                ('is_premium_only', models.BooleanField(default=False)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='videos.videosource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
