# Generated by Django 6.0.2 on 2026-02-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoformat',
            name='format_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
