# Generated by Django 6.0.2 on 2026-02-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_videoformat_format_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoformat",
            name="size_bytes",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Size(bytes)"
            ),
        ),
    ]
