# Generated by Django 6.0.2 on 2026-02-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="history",
            options={"verbose_name_plural": "histories"},
        ),
    ]
