# Generated by Django 6.0.2 on 2026-02-07 19:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('bytes_downloaded', models.BigIntegerField(default=0)),
                ('bytes_total', models.BigIntegerField(blank=True, null=True)),
                ('speed_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('eta_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('output_filename', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downloads', to='videos.videoformat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downloads', to='videos.videosource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
