# Generated by Django 6.0.2 on 2026-02-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_subscription_event_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="provider_customer_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="provider_subscription_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_state",
            field=models.CharField(
                choices=[
                    ("inactive", "Inactive"),
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("canceling", "Canceling"),
                    ("canceled", "Canceled"),
                ],
                default="inactive",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=128, unique=True)),
                ("event_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True, default="")),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription_events",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={},
        ),
    ]
